MK_VERSION_CLIENT_MAJOR:=1
MK_VERSION_CLIENT_MINOR:=0
MK_VERSION_CLIENT_PATCH:=0

MK_VERSION_SERVER_MAJOR:=1
MK_VERSION_SERVER_MINOR:=0
MK_VERSION_SERVER_PATCH:=0

MK_VERSION_CLI_MAJOR:=1
MK_VERSION_CLI_MINOR:=0
MK_VERSION_CLI_PATCH:=0

CPPFLAGS_VERSION_CLIENT:= \
	-DVERSION_CLIENT_MAJOR=$(MK_VERSION_CLIENT_MAJOR) \
	-DVERSION_CLIENT_MINOR=$(MK_VERSION_CLIENT_MINOR) \
	-DVERSION_CLIENT_PATCH=$(MK_VERSION_CLIENT_PATCH)

CPPFLAGS_VERSION_SERVER:= \
	-DVERSION_SERVER_MAJOR=$(MK_VERSION_SERVER_MAJOR) \
	-DVERSION_SERVER_MINOR=$(MK_VERSION_SERVER_MINOR) \
	-DVERSION_SERVER_PATCH=$(MK_VERSION_SERVER_MINOR)

CPPFLAGS_VERSION_CLI:= \
	-DVERSION_CLI_MAJOR=$(MK_VERSION_CLI_MAJOR) \
	-DVERSION_CLI_MINOR=$(MK_VERSION_CLI_MINOR) \
	-DVERSION_CLI_PATCH=$(MK_VERSION_CLI_PATCH)

all: Server Client

Server:
		g++ -o ServerApplication serverMain.cpp Server.cpp CMDHandler.cpp -pthread $(CPPFLAGS_VERSION_SERVER)

Client: 
		g++ -o ClientApplication clientMain.cpp TT_Cli.cpp Client.cpp $(CPPFLAGS_VERSION_CLIENT) \
																      $(CPPFLAGS_VERSION_CLI)

clean:
		rm ClientApplication ServerApplication
